development:
  encryption_key: REPLACE_WITH_32_CHAR_HEX_KEY
  encryption_secret: REPLACE_WITH_32_CHAR_HEX_SECRET
test:
  encryption_key: REPLACE_WITH_32_CHAR_HEX_KEY
  encryption_secret: REPLACE_WITH_32_CHAR_HEX_SECRET